-- Run in the Supabase SQL editor (safe to run again).
--
-- book_parcel saves a booking in one step: customers, parcel, payment and receipt.
-- If anything fails (e.g. the network drops), nothing is saved, so there are no
-- parcels without a payment or receipt. The app calls it with supabase.rpc().
--
-- It runs with the caller's own permissions (security invoker), so the access
-- rules in security.sql still apply.

create or replace function public.book_parcel(
  p_origin_branch_id text,
  p_destination_branch_id text,
  p_category_id text,
  p_weight_kg numeric,
  p_distance_km numeric,
  p_shipping_charge numeric,
  p_sender_name text,
  p_sender_phone text,
  p_receiver_name text,
  p_receiver_phone text,
  p_payment_method text,
  p_mpesa_code text default null
) returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user public.users%rowtype;
  v_business_id text;
  v_sender_id text;
  v_receiver_id text;
  v_parcel public.parcels%rowtype;
  v_payment public.payments%rowtype;
  v_receipt public.receipts%rowtype;
begin
  select * into v_user from public.users where id = auth.uid();
  if not found then
    raise exception 'This account is not an active staff account';
  end if;
  if p_payment_method not in ('CASH', 'MPESA', 'CARD') then
    raise exception 'Unknown payment method %', p_payment_method;
  end if;
  if p_payment_method = 'MPESA' and coalesce(trim(p_mpesa_code), '') = '' then
    raise exception 'M-Pesa transaction code is required';
  end if;
  if p_weight_kg is null or p_weight_kg <= 0 or p_shipping_charge is null or p_shipping_charge <= 0 then
    raise exception 'Weight and charge must be greater than zero';
  end if;

  v_business_id := coalesce(v_user.business_id::text, (select id::text from public.businesses limit 1));

  -- Reuse customers with the same phone number instead of creating duplicates
  select id::text into v_sender_id from public.customers where phone = trim(p_sender_phone) order by id limit 1;
  if v_sender_id is null then
    insert into public.customers (business_id, name, phone)
    select r.business_id, r.name, r.phone
    from jsonb_populate_record(null::public.customers, jsonb_build_object(
      'business_id', v_business_id, 'name', trim(p_sender_name), 'phone', trim(p_sender_phone))) r
    returning id::text into v_sender_id;
  end if;

  select id::text into v_receiver_id from public.customers where phone = trim(p_receiver_phone) order by id limit 1;
  if v_receiver_id is null then
    insert into public.customers (business_id, name, phone)
    select r.business_id, r.name, r.phone
    from jsonb_populate_record(null::public.customers, jsonb_build_object(
      'business_id', v_business_id, 'name', trim(p_receiver_name), 'phone', trim(p_receiver_phone))) r
    returning id::text into v_receiver_id;
  end if;

  -- jsonb_populate_record converts each value to the column's real type
  insert into public.parcels (business_id, sender_id, receiver_id, origin_branch_id, destination_branch_id,
                              category_id, weight_kg, declared_value, is_fragile, shipping_charge, distance_km,
                              status, booked_by)
  select r.business_id, r.sender_id, r.receiver_id, r.origin_branch_id, r.destination_branch_id,
         r.category_id, r.weight_kg, r.declared_value, r.is_fragile, r.shipping_charge, r.distance_km,
         r.status, r.booked_by
  from jsonb_populate_record(null::public.parcels, jsonb_build_object(
    'business_id', v_business_id,
    'sender_id', v_sender_id,
    'receiver_id', v_receiver_id,
    'origin_branch_id', p_origin_branch_id,
    'destination_branch_id', p_destination_branch_id,
    'category_id', p_category_id,
    'weight_kg', p_weight_kg,
    'declared_value', 0,
    'is_fragile', false,
    'shipping_charge', round(p_shipping_charge, 2),
    'distance_km', p_distance_km,
    'status', 'BOOKED',
    'booked_by', auth.uid())) r
  returning * into v_parcel;

  insert into public.payments (parcel_id, business_id, branch_id, amount, payment_method,
                               mpesa_transaction_code, status, received_by, paid_at)
  select r.parcel_id, r.business_id, r.branch_id, r.amount, r.payment_method,
         r.mpesa_transaction_code, r.status, r.received_by, r.paid_at
  from jsonb_populate_record(null::public.payments, jsonb_build_object(
    'parcel_id', v_parcel.id,
    'business_id', v_business_id,
    'branch_id', v_user.branch_id,
    'amount', round(p_shipping_charge, 2),
    'payment_method', p_payment_method,
    'mpesa_transaction_code', case when p_payment_method = 'MPESA' then upper(trim(p_mpesa_code)) end,
    'status', 'COMPLETED',
    'received_by', auth.uid(),
    'paid_at', now())) r
  returning * into v_payment;

  -- receipt_number is generated by the existing database trigger/default
  insert into public.receipts (business_id, branch_id, parcel_id, payment_id, issued_by, issued_at)
  select r.business_id, r.branch_id, r.parcel_id, r.payment_id, r.issued_by, r.issued_at
  from jsonb_populate_record(null::public.receipts, jsonb_build_object(
    'business_id', v_business_id,
    'branch_id', v_user.branch_id,
    'parcel_id', v_parcel.id,
    'payment_id', v_payment.id,
    'issued_by', auth.uid(),
    'issued_at', now())) r
  returning * into v_receipt;

  return jsonb_build_object(
    'parcel_id', v_parcel.id,
    'booking_number', v_parcel.booking_number,
    'receipt_number', v_receipt.receipt_number
  );
end;
$$;

revoke all on function public.book_parcel from public, anon;
grant execute on function public.book_parcel to authenticated;
